In [75]:
#PROBLEM STATMENT -->regression model to check whether the annual income is individual annual income is greater than or equal to 50k or not.

In [76]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [77]:
df=pd.read_csv("/content/census-income .csv")
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,annual_income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [78]:
#EDA
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
annual_income     0
dtype: int64

In [79]:
df.drop_duplicates(inplace=True)

In [80]:
out_liers=["age",'fnlwgt','education-num']#i have not considerd houres per week because of the targeted column
for col in out_liers:
  q1=df[col].quantile(0.25)
  q3=df[col].quantile(0.75)
  iqr=q3-q1
  LB=q1-1.5*iqr
  UB=q3+1.5*iqr
  df=df[(df[col] >LB) &(df[col]<UB)]

In [81]:
#Label encoding
from sklearn.preprocessing import LabelEncoder
Le=LabelEncoder()
for col in df.columns:
  if df[col].dtype =="object":
    df[col]=Le.fit_transform(df[col])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30287 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             30287 non-null  int64
 1   workclass       30287 non-null  int64
 2   fnlwgt          30287 non-null  int64
 3   education       30287 non-null  int64
 4   education-num   30287 non-null  int64
 5   marital-status  30287 non-null  int64
 6   occupation      30287 non-null  int64
 7   relationship    30287 non-null  int64
 8   race            30287 non-null  int64
 9   sex             30287 non-null  int64
 10  capital-gain    30287 non-null  int64
 11  capital-loss    30287 non-null  int64
 12  hours-per-week  30287 non-null  int64
 13  native-country  30287 non-null  int64
 14  annual_income   30287 non-null  int64
dtypes: int64(15)
memory usage: 3.7 MB

In [82]:
x=df.drop("annual_income",axis=1)
y=df['annual_income']

In [83]:
vif=pd.DataFrame()

In [84]:
vif["new_columns"]=x.columns

In [85]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif_values=[]
for i in range(len(x.columns)):
  current_vif_value = variance_inflation_factor(x.values,i) #calculating the vif value
  vif_values.append(current_vif_value)
vif["VIF_Values"] = vif_values
vif

       new_columns  VIF_Values
0              age    9.532053
1        workclass    8.539735
2           fnlwgt    4.958278
3        education    8.077008
4    education-num   21.890839
5   marital-status    4.057499
6       occupation    3.695552
7     relationship    2.641752
8             race   18.265031
9              sex    4.406154
10    capital-gain    1.044773
11    capital-loss    1.063334
12  hours-per-week   12.654078
13  native-country   20.876071

In [86]:
x.drop('education-num',axis=1,inplace=True)

In [88]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif = pd.DataFrame()
vif["new_columns"] = x.columns

vif_values=[]
for i in range(len(x.columns)):
  current_vif_value = variance_inflation_factor(x.values,i) #calculating the vif value
  vif_values.append(current_vif_value)
vif["VIF_Values"] = vif_values
vif

       new_columns  VIF_Values
0              age    9.018687
1        workclass    8.490979
2           fnlwgt    4.923072
3        education    7.399236
4   marital-status    3.987811
5       occupation    3.614424
6     relationship    2.630072
7             race   17.746675
8              sex    4.403517
9     capital-gain    1.036207
10    capital-loss    1.058225
11  hours-per-week   11.918767
12  native-country   20.525107

In [89]:
x.drop('native-country',axis=1,inplace=True)

In [90]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif = pd.DataFrame()
vif["new_columns"] = x.columns

vif_values=[]
for i in range(len(x.columns)):
  current_vif_value = variance_inflation_factor(x.values,i) #calculating the vif value
  vif_values.append(current_vif_value)
vif["VIF_Values"] = vif_values
vif

       new_columns  VIF_Values
0              age    8.554473
1        workclass    8.418542
2           fnlwgt    4.885365
3        education    7.215788
4   marital-status    3.867656
5       occupation    3.606928
6     relationship    2.525632
7             race   15.106547
8              sex    4.357101
9     capital-gain    1.035479
10    capital-loss    1.058105
11  hours-per-week   11.557517

In [91]:
x.drop('race',axis=1,inplace=True)

In [92]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif = pd.DataFrame()
vif["new_columns"] = x.columns

vif_values=[]
for i in range(len(x.columns)):
  current_vif_value = variance_inflation_factor(x.values,i) #calculating the vif value
  vif_values.append(current_vif_value)
vif["VIF_Values"] = vif_values
vif

       new_columns  VIF_Values
0              age    7.756964
1        workclass    8.160748
2           fnlwgt    4.781274
3        education    6.960777
4   marital-status    3.733445
5       occupation    3.595616
6     relationship    2.449379
7              sex    4.230662
8     capital-gain    1.034836
9     capital-loss    1.058070
10  hours-per-week   10.925085

In [93]:
x.drop('hours-per-week',axis=1,inplace=True)

In [94]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif = pd.DataFrame()
vif["new_columns"] = x.columns

vif_values=[]
for i in range(len(x.columns)):
  current_vif_value = variance_inflation_factor(x.values,i) #calculating the vif value
  vif_values.append(current_vif_value)
vif["VIF_Values"] = vif_values
vif

      new_columns  VIF_Values
0             age    6.967361
1       workclass    7.666605
2          fnlwgt    4.697168
3       education    6.626599
4  marital-status    3.721113
5      occupation    3.558876
6    relationship    2.432449
7             sex    3.935290
8    capital-gain    1.033341
9    capital-loss    1.056642

In [95]:
x.drop('workclass',axis=1,inplace=True)

In [96]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif = pd.DataFrame()
vif["new_columns"] = x.columns

vif_values=[]
for i in range(len(x.columns)):
  current_vif_value = variance_inflation_factor(x.values,i) #calculating the vif value
  vif_values.append(current_vif_value)
vif["VIF_Values"] = vif_values
vif

      new_columns  VIF_Values
0             age    6.440120
1          fnlwgt    4.641626
2       education    6.373609
3  marital-status    3.675471
4      occupation    3.202541
5    relationship    2.381376
6             sex    3.772246
7    capital-gain    1.033196
8    capital-loss    1.056615

In [97]:
x.drop('education',axis=1,inplace=True)

In [98]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif = pd.DataFrame()
vif["new_columns"] = x.columns

vif_values=[]
for i in range(len(x.columns)):
  current_vif_value = variance_inflation_factor(x.values,i) #calculating the vif value
  vif_values.append(current_vif_value)
vif["VIF_Values"] = vif_values
vif

      new_columns  VIF_Values
0             age    5.351083
1          fnlwgt    4.522083
2  marital-status    3.543172
3      occupation    3.169695
4    relationship    2.273384
5             sex    3.643518
6    capital-gain    1.033067
7    capital-loss    1.056295

In [99]:
from sklearn.model_selection import train_test_split

In [100]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.75)

In [101]:
from sklearn.linear_model import LogisticRegression

In [102]:
model=LogisticRegression()

In [103]:
model.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [104]:
y_pred=model.predict(x_test)

In [105]:
y_pred

array([0, 1, 0, ..., 0, 0, 1])

In [106]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)*100

79.29212889593238