In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("/content/housing.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  int64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(4), int64(16), object(1)
memory usage: 3.5+ MB

In [4]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [8]:
s = (df["waterfront"] == 0).sum()
s

np.int64(21450)

In [9]:
21612-21450

162

In [11]:
(df['floors']==2).sum()

np.int64(8241)

In [14]:
import pandas as pd

df['date'] = pd.to_datetime(df['date'], format='%Y%m%dT%H%M%S')

In [15]:
df['date']

0       2014-10-13
1       2014-12-09
2       2015-02-25
3       2014-12-09
4       2015-02-18
           ...
21608   2014-05-21
21609   2015-02-23
21610   2014-06-23
21611   2015-01-16
21612   2014-10-15
Name: date, Length: 21613, dtype: datetime64[ns]

In [17]:
da = df.groupby(df['date'].dt.year).size()

In [19]:
dat=df.groupby(df["date"].dt.year).size()
dat

date
2014    14633
2015     6980
dtype: int64

In [23]:
(df['date'].dt.year <1960).sum()

np.int64(0)

In [28]:
(df['price'].max() & df['bedrooms'] >4).count()

np.int64(21613)

In [33]:
#13) The exercise after this contains questions that are based on the housing dataset. What is the price of the most expensive house having more than 4 bathrooms?
df[df['bathrooms'] > 4]['price'].max()

7700000

In [38]:
df1= pd.read_csv("/content/Diamond.csv")
df1.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [ ]:
df1

In [47]:
cu=(df1["clarity"].unique())
cu.sum()

'SI2SI1VS1VS2VVS2VVS1I1IF'

In [48]:
#How many unique values present in the feature clarity?
df1["clarity"].nunique()

8

In [52]:
#Which category in the feature cut has more records?
df1["cut"].value_counts().idxmax()

'Ideal'

In [ ]:
df1.groupby

In [58]:
a=df1.groupby("color")["price"].sum()
# questions mentioned below Which color diamond has the highest sum price?
a.idxmax()

'G'

In [59]:
#Which of the combination of Color and Clarity have a high mean price value?
df1.groupby("Color" and 'clarity')['price'].mean().idxmax()

'SI2'

In [64]:
((df1['x'] == 0) & (df1['y'] == 0) & (df1['z'] == 0)).sum()

np.int64(7)

In [66]:
df2=pd.read_csv('/content/ToyotaCorolla.csv')
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1436 non-null   int64
 1   Price       1436 non-null   int64
 2   Age         1336 non-null   float64
 3   KM          1436 non-null   int64
 4   FuelType    1336 non-null   object
 5   HP          1436 non-null   int64
 6   MetColor    1286 non-null   float64
 7   Automatic   1436 non-null   int64
 8   CC          1436 non-null   int64
 9   Doors       1436 non-null   int64
 10  Weight      1436 non-null   int64
dtypes: float64(2), int64(8), object(1)
memory usage: 123.5+ KB

In [70]:
df2.head()

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,0,13500,23.0,46986,Diesel,90,1.0,0,2000,3,1165
1,1,13750,23.0,72937,Diesel,90,1.0,0,2000,3,1165
2,2,13950,24.0,41711,Diesel,90,NaN,0,2000,3,1165
3,3,14950,26.0,48000,Diesel,90,0.0,0,2000,3,1165
4,4,13750,30.0,38500,Diesel,90,0.0,0,2000,3,1170

In [68]:
df2["FuelType"].value_counts()

FuelType
Petrol    1177
Diesel     144
CNG         15
Name: count, dtype: int64

In [77]:
#Choose the correct CC value having the second lowest price?
df2.groupby("CC")['Price'].sum().sort_values().index[1]

np.int64(1332)

In [80]:
#Use the ToyotaCorollaX.csv of size : 1436 x 11 for the questions mentioned below Choose the correct Doors type having the second highest mean price?
df2.groupby("Doors")['Price'].mean().sort_values(ascending=False).index[1]

np.int64(3)